### ISSUE TITLE
v0.0.9 contains a case-insensitive file name collision

### ISSUE THREAD

**Issue by dmitshur** [alessiosavi/GoGPUtils#2]
**Describe the bug**
It's not possible to use v0.0.9 in module mode because it contains "tests/fileutils/FindMe.txt" and "tests/fileutils/findme.txt" files that cause a case-insensitive file name collision. The go command rejects it as a result.

**To Reproduce**

```
$ cd $(mktemp -d)
$ export GOPATH=$(pwd)
$ export GO111MODULE=on
$ export GOPROXY=direct
$ export GOSUMDB=off
$ go get -d github.com/alessiosavi/GoGPUtils@v0.0.9
go: finding github.com/alessiosavi/GoGPUtils v0.0.9
go: downloading github.com/alessiosavi/GoGPUtils v0.0.9
go: extracting github.com/alessiosavi/GoGPUtils v0.0.9
-> unzip /tmp/NPdspiwu/pkg/mod/cache/download/github.com/alessiosavi/!go!g!p!utils/@v/v0.0.9.zip: case-insensitive file name collision: "tests/fileutils/FindMe.txt" and "tests/fileutils/findme.txt"
go get github.com/alessiosavi/GoGPUtils@v0.0.9: unzip /tmp/NPdspiwu/pkg/mod/cache/download/github.com/alessiosavi/!go!g!p!utils/@v/v0.0.9.zip: case-insensitive file name collision: "tests/fileutils/FindMe.txt" and "tests/fileutils/findme.txt"
```

**Expected behavior**
It should work without an error.

**Additional context**
There is an open issue in the Go issue tracker about documenting the restrictions on contents that can be a part of modules. See https://github.com/golang/go/issues/33778.

/cc @jayconrod FYI.

**Comment by alessiosavi** [comment]
Fixed in d1c4229d0d45e5a2600cac192295ca406cd4946c.

Thank you so much for the effort during the analysis (: :+1:
